dre/urls.py
from dre import views
from django.urls import path

app_name = 'dre'

urlpatterns = [
    path('<user>/', views.list, name='list'),
    path('<user>/add/', views.create, name='add'),
    path('<user>/<ano>/', views.detail, name='detail'),
    path('<user>/<ano>/edit/', views.edit, name='edit'),
    path('<user>/<ano>/delete/', views.delete, name='delete'),
    path('<user>/api/<ano>/', views.api_save, name='api_save')
]

graficos/urls.py
from graficos import views
from django.urls import path

app_name = 'graficos'

urlpatterns = [
    path('dre/<user>/', views.grafico_dre, name='grafico_dre'),
    path('inicial/<user>/', views.ped_inicial, name='ped_inicial'),
    path('gestao/<user>/', views.ped_gestao, name='ped_gestao'),
    path('desempenho/<user>/', views.ped_desempenho, name='ped_desempenho'),
    path('diagnostico/<user>/', views.ped_diagnostico, name='ped_diagnostico'),
    path('diagnostico/externo/<user>/', views.diagnostico_amb_ext, name='diagnostico_amb_ext'),
    path('diagnostico/interno/<user>/', views.diagnostico_amb_int, name='diagnostico_amb_int')
]

icon/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from core.views import home
from django.urls import path

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    # url(r'^reset/', include('password_reset.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^dre/', include('dre.urls', namespace='dre')),
    path('objetivos/', include('objetivos.urls')),
    path('swot/', include('swot.urls')),
    path('graficos/', include('graficos.urls')),
    path('vendas/', include('vendas.urls')),
    path('processos_produtivo/',include('processos_produtivo.urls')),
    path('pessoa/',include('pessoa.urls')),
    path('processos_produtivo/', include('processos_produtivo.urls')),
    path('pessoa/', include('pessoa.urls')),
    path('mapa/', include('mapa.urls')),
]

mapa/urls.py
from django.urls import path
from . import views

app_name = 'mapa'

urlpatterns = [
    path('mapa_estrategico/<user>/', views.mapa_estrategico, name='mapa_estrategico'),
    
]

pessoa/urls.py
from django.urls import path
from . import views

app_name = 'pessoa'

urlpatterns = [
    path('analise_desempenho_pessoas/<user>/', views.analise_desempenho_pessoas, name='analise_desempenho_pessoas'),
    path('analise_desempenho_pessoas/<user>/salvar/', views.salvar_objetivo_de_pessoas, name='salvar_objetivo_de_pessoas'),
    path('painel_desempenho_pessoas/<user>/', views.painel_desempenho_pessoas, name='painel_desempenho_pessoas'),
    path('multi_pessoas/<user>/', views.multi_pessoas, name='multi_pessoas'),
    path ('dashboard_pessoas/<user>/', views.dashboard_pessoas, name='dashboard_pessoas' ),
    path('objetivos/competencia/<user>/', views.competencia, name='competencia'),
    path('objetivos/engajamento/<user>/', views.engajamento, name='engajamento'),
    path('objetivos/retencao/<user>/', views.retencao, name='retencao'),

]

swot/urls.py
from swot import views
from django.urls import path

app_name = 'swot'

urlpatterns = [
    path('questionario/<user>/', views.questionario, name='questionario'),
    path('analise_swot/<user>/', views.analise_swot, name='analise_swot'),
    path('questionario/<user>/salvar/', views.salvar_resposta_questionario, name='salvar_resposta_questionario'),
    path('concorrencia/<user>/', views.swot_concorrencia, name='swot_concorrencia'),
    path('concorrencia/<user>/salvar/', views.salvar_analise_concorrencia, name='salvar_analise_concorrencia'),
    path('concorrencia/<user>/salvar/concorrente/', views.salvar_concorrente, name='salvar_concorrente'),
    path('concorrencia/<user>/salvar_nome/', views.alterar_nome_concorrente, name='salvar_nome_concorrente'),
    path('clientes/<user>/', views.swot_clientes, name='swot_clientes' ),
    path('clientes/<user>/salvar/', views.salvar_analise_clientes, name='salvar_analise_clientes' ),
    path('clientes/<user>/salvar/clientes/', views.salvar_clientes, name='salvar_clientes' ),
    path('clientes/<user>/salvar_nome/', views.alterar_nome_cliente, name='salvar_nome_cliente'),
    path('fornecedores/<user>/', views.swot_fornecedores, name='swot_fornecedores' ),
    path('fornecedores/<user>/salvar/', views.salvar_analise_fornecedores, name='salvar_analise_fornecedores' ),
    path('fornecedores/<user>/salvar/fornecedores/', views.salvar_fornecedores, name='salvar_fornecedores' ),
    path('fornecedores/<user>/salvar_nome/', views.alterar_nome_fornecedor, name='salvar_nome_fornecedor'),
    path('macro/<user>/', views.swot_macro, name='swot_macro' ),
    path('macro/<user>/salvar/', views.salvar_analise_macro, name='salvar_analise_macro' ),
    path('macro/<user>/salvar/fornecedores/', views.salvar_macro, name='salvar_macro' ),
]

vendas/urls.py
from django.urls import path
from . import views

app_name = 'vendas'

urlpatterns = [
    path('objetivo_vendas/<user>/', views.definir_objetivo_de_vendas, name='analise_desempenho_vendas'),
    path('objetivo_vendas/<user>/salvar/', views.salvar_objetivo_de_vendas, name='salvar_desempenho_vendas'),
    path('desempenho_vendas/<user>/', views.painel_desempenho_vendas, name='painel_desempenho_vendas'),
    path('dashboard_vendas/<user>/', views.dashboard_vendas, name='dashboard_vendas' ),
    path('vendas/<user>/<ano>/', views.detail_vendas, name='vendas_detail' ),
    path('objetivos/mkt_relacionamento/<user>/', views.mkt_relacionamento, name='mkt_relacionamento'),
    path('objetivos/metas_vendas/<user>/', views.metas_vendas, name='metas_vendas'),
    path('objetivos/satisfacao_clientes/<user>/', views.satisfacao_clientes, name='satisfacao_clientes'),

]

graficos/models.py
from django.db import models

# Create your models here.

graficos/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from accounts.decorators import is_allowed
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from objetivos.utils import calcula_campos_dinamicos
from dre.models import Dre
from objetivos.models import *
from swot.models import *
from .utils import *
from swot.utils import calcula_competitividade

# Create your views here.
@login_required
@is_allowed
def grafico_dre(request, user):
    # Objetos do banco de dados
    owner = get_object_or_404(User, username=user)
    dres = Dre.objects.all().filter(user=owner).order_by('ano_exercicio')
    dicio_retorno = {
        'anos': [],
        'receitas': [],
        'lucros': [],
        'rentabilidades': [],
        'ebitdas': [],
        'lucros_liquidos': [],
        'despesas': []
    }

    for dre in dres:
        campos_dinamicos = calcula_campos_dinamicos(dre)

        dicio_retorno['anos'].append(dre.ano_exercicio)
        dicio_retorno['receitas'].append(campos_dinamicos['receita_bruta'])
        dicio_retorno['lucros'].append(campos_dinamicos['lucro_bruto'])
        dicio_retorno['rentabilidades'].append(campos_dinamicos['rentabilidade'])
        dicio_retorno['ebitdas'].append(campos_dinamicos['ebitda'])
        dicio_retorno['lucros_liquidos'].append(campos_dinamicos['lucro_liquido'])
        dicio_retorno['despesas'].append(campos_dinamicos['custo_total'])

    return render(request, 'graficos/grafico_dre.html', dicio_retorno)

@login_required
@is_allowed
def ped_inicial(request, user):
    # Objetos do banco de dados
    owner = get_object_or_404(User, username=user)
    dre = Dre.objects.all().filter(user=owner).order_by('-ano_exercicio')[0]

    total_preenchimento = 0
    total_smile_points = 0

    # Verifica objetivos de receitas
    # Espera-se um range de -3/3 smiles points
    try:
        objetivo = ObjetivoReceitas.objects.get(dre_base=dre)
        analise_objetivo = AnaliseObjetivoReceitas.objects.get(objetivo_receitas_base=objetivo)
        total_preenchimento += 1
        total_smile_points += calcula_smile_points(analise_objetivo.smile_receita_bruta)
        total_smile_points += calcula_smile_points(analise_objetivo.smile_crescimento_quatro)
        total_smile_points += calcula_smile_points(analise_objetivo.smile_crescimento)
    except:
        pass

    # Verifica objetivos de rentabilidade
    # Espera-se um range de -6/6 smile points
    try:
        objetivo = ObjetivoRentabilidade.objects.get(dre_base=dre)
        analise_objetivo = AnaliseObjetivoRentabilidade.objects.get(objetivo_rentabilidade_base=objetivo)
        total_preenchimento += 1
        total_smile_points += calcula_smile_points(analise_objetivo.smile_lucro_liquido)
        total_smile_points += calcula_smile_points(analise_objetivo.smile_rentabilidade_media)
        total_smile_points += calcula_smile_points(analise_objetivo.smile_rentabilidade_ultimo)
        total_smile_points += calcula_smile_points(analise_objetivo.smile_rentabilidade_comparada)
        total_smile_points += calcula_smile_points(analise_objetivo.smile_ebitda_medio)
        total_smile_points += calcula_smile_points(analise_objetivo.smile_ebitda_ultimo)
    except:
        pass

    # Verifica objetivos de endividamento
    # Espera-se um range de -3/3 smiles points
    try:
        objetivo = ObjetivoEndividamentos.objects.get(dre_base=dre)
        analise_objetivo = AnaliseObjetivoEndividamento.objects.get(objetivo_endividamento_base=objetivo)
        total_preenchimento += 1
        total_smile_points += calcula_smile_points(smile_divida)
        total_smile_points += calcula_smile_points(smile_taxa_divida_lucro)
        total_smile_points += calcula_smile_points(smile_inadimplencia)
    except:
        pass

    porcentagem_financeiro = 1
    porcentagem_financeiro += 9 * total_preenchimento
    if total_smile_points > 0:
        porcentagem_financeiro += 6 * total_smile_points

    questoes = Questao.objects.all()
    respostas = []
    pontos_respostas = 0
    for questao in questoes:
        try:
            resposta = Resposta.objects.get(questao=questao, user=owner)
            respostas.append(resposta)
            if resposta.resposta == 'Sim':
                pontos_respostas += 1
            elif resposta.resposta == 'Não':
                pontos_respostas -= 1
            else:
                pass
        except:
            pass

    porcentagem_sobrevivencia = len(respostas) * (30/len(questoes))
    if pontos_respostas > 0:
        porcentagem_sobrevivencia += pontos_respostas * (70/len(questoes))

    # Objetos do banco de dados
    owner = get_object_or_404(User, username=user)
    dre = Dre.objects.all().filter(user=owner).order_by('-ano_exercicio')[0]

    total_preenchimento = 0
    total_smile_points = 0

    # Verifica objetivos de receitas
    # Espera-se um range de -3/3 smiles points
    try:
        objetivo = ObjetivoReceitas.objects.get(dre_base=dre)
        analise_objetivo = AnaliseObjetivoReceitas.objects.get(objetivo_receitas_base=objetivo)
        total_preenchimento += 1
        total_smile_points += calcula_smile_points(analise_objetivo.smile_receita_bruta)
        total_smile_points += calcula_smile_points(analise_objetivo.smile_crescimento_quatro)
        total_smile_points += calcula_smile_points(analise_objetivo.smile_crescimento)
    except:
        pass

    # Verifica objetivos de rentabilidade
    # Espera-se um range de -6/6 smile points
    try:
        objetivo = ObjetivoRentabilidade.objects.get(dre_base=dre)
        analise_objetivo = AnaliseObjetivoRentabilidade.objects.get(objetivo_rentabilidade_base=objetivo)
        total_preenchimento += 1
        total_smile_points += calcula_smile_points(analise_objetivo.smile_lucro_liquido)
        total_smile_points += calcula_smile_points(analise_objetivo.smile_rentabilidade_media)
        total_smile_points += calcula_smile_points(analise_objetivo.smile_rentabilidade_ultimo)
        total_smile_points += calcula_smile_points(analise_objetivo.smile_rentabilidade_comparada)
        total_smile_points += calcula_smile_points(analise_objetivo.smile_ebitda_medio)
        total_smile_points += calcula_smile_points(analise_objetivo.smile_ebitda_ultimo)
    except:
        pass

    # Verifica objetivos de endividamento
    # Espera-se um range de -3/3 smiles points
    try:
        objetivo = ObjetivoEndividamentos.objects.get(dre_base=dre)
        analise_objetivo = AnaliseObjetivoEndividamento.objects.get(objetivo_endividamento_base=objetivo)
        total_preenchimento += 1
        total_smile_points += calcula_smile_points(smile_divida)
        total_smile_points += calcula_smile_points(smile_taxa_divida_lucro)
        total_smile_points += calcula_smile_points(smile_inadimplencia)
    except:
        pass

    porcentagem_gestao = 1
    porcentagem_gestao += 33 * total_preenchimento


    porcentagem_resultado = 4
    if total_smile_points > 0:
        porcentagem_resultado += 8 * total_smile_points

    dicio_retorno = {'porcentagem_gestao': int((porcentagem_financeiro+porcentagem_sobrevivencia+porcentagem_gestao+porcentagem_resultado)/4),
                     'porcentagem_desempenho': int((porcentagem_gestao+porcentagem_resultado)/2)}
    return render(request, 'graficos/ped0_0.html', dicio_retorno)

@login_required
@is_allowed
def ped_gestao(request, user):
    # Objetos do banco de dados
    owner = get_object_or_404(User, username=user)
    dre = Dre.objects.all().filter(user=owner).order_by('-ano_exercicio')[0]

    total_preenchimento = 0
    total_smile_points = 0

    # Verifica objetivos de receitas
    # Espera-se um range de -3/3 smiles points
    try:
        objetivo = ObjetivoReceitas.objects.get(dre_base=dre)
        analise_objetivo = AnaliseObjetivoReceitas.objects.get(objetivo_receitas_base=objetivo)
        total_preenchimento += 1
        total_smile_points += calcula_smile_points(analise_objetivo.smile_receita_bruta)
        total_smile_points += calcula_smile_points(analise_objetivo.smile_crescimento_quatro)
        total_smile_points += calcula_smile_points(analise_objetivo.smile_crescimento)
    except:
        pass

    # Verifica objetivos de rentabilidade
    # Espera-se um range de -6/6 smile points
    try:
        objetivo = ObjetivoRentabilidade.objects.get(dre_base=dre)
        analise_objetivo = AnaliseObjetivoRentabilidade.objects.get(objetivo_rentabilidade_base=objetivo)
        total_preenchimento += 1
        total_smile_points += calcula_smile_points(analise_objetivo.smile_lucro_liquido)
        total_smile_points += calcula_smile_points(analise_objetivo.smile_rentabilidade_media)
        total_smile_points += calcula_smile_points(analise_objetivo.smile_rentabilidade_ultimo)
        total_smile_points += calcula_smile_points(analise_objetivo.smile_rentabilidade_comparada)
        total_smile_points += calcula_smile_points(analise_objetivo.smile_ebitda_medio)
        total_smile_points += calcula_smile_points(analise_objetivo.smile_ebitda_ultimo)
    except:
        pass

    # Verifica objetivos de endividamento
    # Espera-se um range de -3/3 smiles points
    try:
        objetivo = ObjetivoEndividamentos.objects.get(dre_base=dre)
        analise_objetivo = AnaliseObjetivoEndividamento.objects.get(objetivo_endividamento_base=objetivo)
        total_preenchimento += 1
        total_smile_points += calcula_smile_points(smile_divida)
        total_smile_points += calcula_smile_points(smile_taxa_divida_lucro)
        total_smile_points += calcula_smile_points(smile_inadimplencia)
    except:
        pass

    porcentagem_financeiro = 1

graficos/templates/graficos/diagnostico_amb_ext.html
{% extends 'base.html' %}

{% block content %}
{% load l10n %}
<br>
<hr>
<br>
        <div class="btn-group mr-2">
             <a href="{% url 'graficos:ped_diagnostico' user=request.user %}" class="href"><button type="button" class="btn btn-sm btn-outline-info">Anterior</button></a>
             <a href="{% url 'graficos:diagnostico_amb_int' user=request.user %}" class="href"><button type="button" class="btn btn-sm btn-outline-info">Próximo</button></a>
          </div>
<br>
<br>
<hr>
<div class="container-responsive">
        <div class="row">
            <div class="col-12">
                <div class="card-responsive">
                      <div class="card-header bg-secondary text-white">
                        <h2 class="text-center">Diagnostico de Ambiente Externo</h2>
                    </div>
                    <div class="container-responsive">
                            <div class="row">
                                <div class="col-8">
                                    <div class="card-columns">
                                        <div class="card border-light">
                                            <div id="chart_div1"></div>
                                            <div class="card-body">
                                                <a href="{% url 'swot:swot_concorrencia' user=request.user %}"><button class="btn  btn-primary shadow p-3 mb-5  rounded" style="width: 200px;"><h5>CONCORRENTES</h5></button></a>
                                            </div>
                                        </div>
                         <div class="container-responsive">
                                <div class="col-8">
                                    <div class="card-columns">
                                        <div class="card border-light">
                                            <div id="chart_div2"></div>
                                            <div class="card-body">
                                                <a href="{% url 'swot:swot_clientes' user=request.user %}"><button class="btn  btn-primary  shadow p-3 mb-5  rounded" style="width: 200px;"><h5>CLIENTES</h5></button></a>
                                            </div>
                                        </div>
                        <div class="container-responsive"style="margin-left:210px;">
                                <div class="col-8">
                                    <div class="card-columns">
                                        <div class="card border-light">
                                            <div id="chart_div3"></div>
                                            <div class="card-body">
                                                <a href="{% url 'swot:swot_fornecedores' user=request.user %}"><button class="btn  btn-primary shadow p-3 mb-5  rounded" style="width: 200px;"><h5>FORNECEDORES</h5></button></a>
                                            </div>
                                        </div>
                        <div class="container-responsive">
                                <div class="col-8">
                                    <div class="card-columns" style="margin-left:230px;">
                                        <div class="card border-light">
                                            <div id="chart_div4"></div>
                                            <div class="card-body">
                                                <a href="{% url 'swot:swot_macro' user=request.user %}"><button class="btn  btn-primary  shadow p-3 mb-5  rounded" style="width: 200px;"><h5>MACRO AMBIENTE</h5></button></a
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                 </div>
             </div>
         </div>


{% endblock content %}

{% block extras_js %}
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
   <script type="text/javascript">
      google.charts.load('current', {'packages':['gauge']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {

        var data = google.visualization.arrayToDataTable([
          ['Label', 'Value'],
          ['Gestão', {{concorrencia|unlocalize}}],
        ]);

        var options = {
          width: 270, height: 270,
          redFrom: 0, redTo: 34,
          yellowFrom:34, yellowTo: 68,
          greenFrom:68,greenTo:100,

          minorTicks: 5
        };

        var chart = new google.visualization.Gauge(document.getElementById('chart_div'));

        chart.draw(data, options);
      }
    </script>
   <script type="text/javascript">
      google.charts.load('current', {'packages':['gauge']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {

        var data = google.visualization.arrayToDataTable([
          ['Label', 'Value'],
          ['Gestão', {{concorrencia|unlocalize}}],
        ]);

        var options = {
          width: 270, height: 270,
          redFrom: 0, redTo: 34,
          yellowFrom:34, yellowTo: 68,
          greenFrom:68,greenTo:100,
          minorTicks: 5
        };

        var chart = new google.visualization.Gauge(document.getElementById('chart_div1'));

        chart.draw(data, options);

      }
    </script>
   <script type="text/javascript">
      google.charts.load('current', {'packages':['gauge']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {

        var data = google.visualization.arrayToDataTable([
          ['Label', 'Value'],
          ['Gestão', {{clientes|unlocalize}}],
        ]);

        var options = {
          width: 270, height: 270,
          redFrom: 0, redTo: 34,
          yellowFrom:34, yellowTo: 68,
          greenFrom:68,greenTo:100,
          minorTicks: 5
        };

        var chart = new google.visualization.Gauge(document.getElementById('chart_div2'));

        chart.draw(data, options);

      }
    </script>
   <script type="text/javascript">
      google.charts.load('current', {'packages':['gauge']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {

        var data = google.visualization.arrayToDataTable([
          ['Label', 'Value'],
          ['Gestão', {{fornecedores|unlocalize}}],
        ]);

        var options = {
          width: 270, height: 270,
          redFrom: 0, redTo: 34,
          yellowFrom:34, yellowTo: 68,
          greenFrom:68,greenTo:100,
          minorTicks: 5
        };

        var chart = new google.visualization.Gauge(document.getElementById('chart_div3'));

        chart.draw(data, options);

      }
    </script>
   <script type="text/javascript">
      google.charts.load('current', {'packages':['gauge']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {

        var data = google.visualization.arrayToDataTable([
          ['Label', 'Value'],
          ['Gestão', {{analise|unlocalize}}],
        ]);

        var options = {
          width: 270, height: 270,
          redFrom: 0, redTo: 34,
          yellowFrom:34, yellowTo: 68,
          greenFrom:68,greenTo:100,
          minorTicks: 5
        };

        var chart = new google.visualization.Gauge(document.getElementById('chart_div4'));

        chart.draw(data, options);

      }
    </script>
   <script type="text/javascript">
      google.charts.load('current', {'packages':['gauge']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {

        var data = google.visualization.arrayToDataTable([
          ['Label', 'Value'],
          ['Gestão', {{concorrencia|unlocalize}}],
        ]);

        var options = {
          width: 270, height: 270,
          redFrom: 0, redTo: 34,
          yellowFrom:34, yellowTo: 68,
          greenFrom:68,greenTo:100,
          minorTicks: 5
        };

        var chart = new google.visualization.Gauge(document.getElementById('chart_div5'));

        chart.draw(data, options);

      }
    </script>
{% endblock extras_js %}

graficos/templates/graficos/ped1_0.html
{% extends 'base.html' %}

{% block content %}
{% load l10n %}
<br>
<hr>
<div class="container">
        <div class="row">
            <div class="col-12">
                <div class="card">
                      <div class="card-header bg-info text-white">
                        <h2 class="text-center">Escolha o Diágnostico</h2>
                         <div class="card-body">
                        <a href="{% url 'swot:analise_swot' user=request.user %}"><button class="btn  btn-primary  shadow p-2 mb-2  rounded" style="margin-left: 370px; width: 250px;"><h4>Análise SWOT</h4></button></a>
                    </div>
                    </div>
  <div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card-columns">
                <div class="card border-light">
                    <div id="chart_div"></div>
                    <div class="card-body">
                        <a href="{% url 'graficos:diagnostico_amb_ext' user=request.user %}"><button class="btn  btn-primary shadow p-3 mb-5  rounded" style="width: 250px;"><h4>Ambiente Externo</h4></button></a>
                    </div>
                </div>
                <div class="card border-light">
                  <div id="chart_div2"></div>
                    <div class="card-body">
                        <a href="{% url 'swot:questionario' user=request.user %}"><button class="btn  btn-primary  shadow p-3 mb-5  rounded" style="width: 250px;"><h4>Sobrevivencia</h4></button></a>
                    </div>
                    </div>
                <div class="card border-light">
                    <div id="chart_div1"></div>
                    <div class="card-body">
                        <a href="{% url 'graficos:diagnostico_amb_int' user=request.user %}"><button class="btn  btn-primary  shadow p-3 mb-5  rounded" style="width: 250px;"><h4>Ambiente Interno</h4></button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block extras_js %}
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
   <script type="text/javascript">
      google.charts.load('current', {'packages':['gauge']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {

        var data = google.visualization.arrayToDataTable([
          ['Label', 'Value'],
          ['', {{ambiente_externo|unlocalize}}],

        ]);

        var options = {
          width: 290, height: 290,
          redFrom: 0, redTo: 34,
          yellowFrom:34, yellowTo: 68,
          greenFrom:68,greenTo:100,
          minorTicks: 5
        };

        var chart = new google.visualization.Gauge(document.getElementById('chart_div'));

        chart.draw(data, options);
      }
    </script>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
   <script type="text/javascript">
      google.charts.load('current', {'packages':['gauge']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {

        var data = google.visualization.arrayToDataTable([
          ['Label', 'Value'],
          ['', {{porcentagem_sobrevivencia|unlocalize}}],

        ]);

        var options = {
          width: 290, height: 290,
          redFrom: 0, redTo: 34,
          yellowFrom:34, yellowTo: 68,
          greenFrom:68,greenTo:100,
          minorTicks: 5
        };

        var chart = new google.visualization.Gauge(document.getElementById('chart_div2'));

        chart.draw(data, options);
      }
    </script>
<script type="text/javascript">
      google.charts.load('current', {'packages':['gauge']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {

        var data = google.visualization.arrayToDataTable([
          ['Label', 'Value'],
          ['', {{porcentagem_financeiro}}],

        ]);

        var options = {
          width: 290, height: 290,
          redFrom: 0, redTo: 34,
          yellowFrom:34, yellowTo: 68,
          greenFrom:68,greenTo:100,
          minorTicks: 5
        };

        var chart = new google.visualization.Gauge(document.getElementById('chart_div1'));

        chart.draw(data, options);
      }
</script>
{% endblock extras_js %}