dre/urls.py
from dre import views
from django.urls import path

app_name = 'dre'

urlpatterns = [
    path('<user>/', views.list, name='list'),
    path('<user>/add/', views.create, name='add'),
    path('<user>/<ano>/', views.detail, name='detail'),
    path('<user>/<ano>/edit/', views.edit, name='edit'),
    path('<user>/<ano>/delete/', views.delete, name='delete'),
    path('<user>/api/<ano>/', views.api_save, name='api_save')
]

graficos/urls.py
from graficos import views
from django.urls import path

app_name = 'graficos'

urlpatterns = [
    path('dre/<user>/', views.grafico_dre, name='grafico_dre'),
    path('inicial/<user>/', views.ped_inicial, name='ped_inicial'),
    path('gestao/<user>/', views.ped_gestao, name='ped_gestao'),
    path('desempenho/<user>/', views.ped_desempenho, name='ped_desempenho'),
    path('diagnostico/<user>/', views.ped_diagnostico, name='ped_diagnostico'),
    path('diagnostico/externo/<user>/', views.diagnostico_amb_ext, name='diagnostico_amb_ext'),
    path('diagnostico/interno/<user>/', views.diagnostico_amb_int, name='diagnostico_amb_int')
]

icon/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from core.views import home
from django.urls import path

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    # url(r'^reset/', include('password_reset.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^dre/', include('dre.urls', namespace='dre')),
    path('objetivos/', include('objetivos.urls')),
    path('swot/', include('swot.urls')),
    path('graficos/', include('graficos.urls')),
    path('vendas/', include('vendas.urls')),
    path('processos_produtivo/',include('processos_produtivo.urls')),
    path('pessoa/',include('pessoa.urls')),
    path('processos_produtivo/', include('processos_produtivo.urls')),
    path('pessoa/', include('pessoa.urls')),
    path('mapa/', include('mapa.urls')),
]

objetivos/urls.py
from django.urls import path
from . import views

app_name = 'objetivos'

urlpatterns = [
    path('receitas/<user>/', views.definir_objetivo_de_receitas, name='objetivo_de_receitas'),
    path('receitas/<user>/salvar/', views.salvar_objetivo_de_receitas, name='salvar_objetivo_de_receitas'),
    path('rentabilidade/<user>/', views.definir_objetivo_de_rentabilidade, name='objetivo_de_rentabilidade'),
    path('rentabilidade/<user>/salvar/', views.salvar_objetivo_de_rentabilidade, name='salvar_objetivo_de_rentabilidade'),
    path('endividamento/<user>/', views.definir_objetivo_de_endividamento, name='objetivo_de_endividamento'),
    path('endividamento/<user>/salvar/', views.salvar_objetivo_de_endividamento, name='salvar_objetivo_de_endividamento'),
    path('analise/<user>/', views.analise_desempenho_financeiro, name='analise_desempenho_financeiro'),
    path('analise/<user>/salvar/', views.salvar_analise_desempenho_financeiro, name='salvar_analise_desempenho_financeiro'),
    path('custos/<user>/', views.definir_objetivo_de_custos, name='objetivo_de_custos'),
    path('custos/<user>/salvar/', views.salvar_objetivo_de_custos, name='salvar_objetivo_de_custos'),
    path('orcamento/<user>/', views.definir_orcamento_mensal, name='definir_orcamento_mensal'),
    path('orcamento/<user>/salvar/', views.salvar_orcamento_mensal, name='salvar_orcamento_mensal'),
]

objetivos/views.py
from django.shortcuts import render, get_object_or_404
from accounts.decorators import is_allowed
from django.contrib.auth.models import User
from dre.models import Dre
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from .models import *
from .utils import select_smile, calcula_campos_dinamicos
from django.http import HttpResponse
from datetime import datetime

# Create your views here.
@login_required
@is_allowed
def definir_objetivo_de_receitas(request, user):
    # Objetos do banco de dados
    owner = get_object_or_404(User, username=user)
    dre = Dre.objects.all().filter(user=owner).order_by('-ano_exercicio')[0]
    objetivo = ObjetivoReceitas.objects.get_or_create(dre_base=dre)[0]
    analise_objetivo = AnaliseObjetivoReceitas.objects.get_or_create(objetivo_receitas_base=objetivo)[0]

    # Campos para exibição
    receita_bruta = dre.receita_servico + dre.receita_produto + dre.outras_receitas
    try:
        dre_passado = Dre.objects.get(user=owner, ano_exercicio=dre.ano_exercicio-3)
        receita_bruta_passado = dre_passado.receita_servico + dre_passado.receita_produto + dre_passado.outras_receitas
        crescimento_quatro = receita_bruta - receita_bruta_passado
        crescimento = (crescimento_quatro / receita_bruta_passado) * 100
    except Exception as e:
        crescimento_quatro = 0.0
        crescimento = 0.0
    #tags = {
    #    '1.0': {'text': 'Estável','value': 1.0},
    #    '1.05': {'text': '5%','value': 1.05},
    #    '1.1': {'text': '10%','value': 1.10},
    #}

    # Campo porcentagem
    #tag_destaque = []
    #tag_destaque.append(tags[str(objetivo.percentage)])
    #del tags[str(objetivo.percentage)]
    #for key in tags:
    #    tag_destaque.append(tags[key])

    # Campos smile
    smiles = {}
    smiles['smile_receita_bruta'] = select_smile(analise_objetivo.smile_receita_bruta)
    smiles['smile_crescimento_quatro'] = select_smile(analise_objetivo.smile_crescimento_quatro)
    smiles['smile_crescimento'] = select_smile(analise_objetivo.smile_crescimento)

    dicio_retorno = {'receita': receita_bruta,  'smiles':smiles,
                     'receita_': receita_bruta * objetivo.percentage,
                     'crescimento_quatro': crescimento_quatro,
                     'crescimento': crescimento, 'objetivo_atual': (objetivo.percentage-1)*100}
    return render(request, 'objetivos/def_objetivos_receitas.html', dicio_retorno)

@login_required
@csrf_exempt
@is_allowed
def salvar_objetivo_de_receitas(request, user):
    if request.method == 'POST':
        # Objetos do banco de dados
        owner = get_object_or_404(User, username=user)
        dre = Dre.objects.all().filter(user=owner).order_by('-ano_exercicio')[0]
        objetivo = ObjetivoReceitas.objects.get_or_create(dre_base=dre)[0]
        analise_objetivo = AnaliseObjetivoReceitas.objects.get_or_create(objetivo_receitas_base=objetivo)[0]

        # Atualização de campos
        objetivo.percentage = float(request.POST['percentage'])
        analise_objetivo.smile_receita_bruta = request.POST['smile_receita_bruta']
        analise_objetivo.smile_crescimento_quatro = request.POST['smile_crescimento_quatro']
        analise_objetivo.smile_crescimento = request.POST['smile_crescimento']

        # Salvamento no banco de dados
        objetivo.save()
        analise_objetivo.save()
    return HttpResponse('')

@login_required
@is_allowed
def definir_objetivo_de_rentabilidade(request, user):
    # Objetos do banco de dados
    owner = get_object_or_404(User, username=user)
    dre = Dre.objects.all().filter(user=owner).order_by('-ano_exercicio')[0]
    objetivo = ObjetivoRentabilidade.objects.get_or_create(dre_base=dre)[0]
    analise_objetivo = AnaliseObjetivoRentabilidade.objects.get_or_create(objetivo_rentabilidade_base=objetivo)[0]

    # Campos para exibição
    campos_dinamicos =  calcula_campos_dinamicos(dre)
    receita_bruta = campos_dinamicos['receita_bruta']
    lucro_liquido = campos_dinamicos['lucro_liquido']
    count = 1
    ebitda_total = campos_dinamicos['ebitda']
    rentabilidade_total = campos_dinamicos['rentabilidade']
    for i in range(1,4):
        try:
            novo_dre = Dre.objects.get(ano_exercicio=dre.ano_exercicio-i)
            novos_campos_dinamicos = calcula_campos_dinamicos(novo_dre)
            ebitda_total += novos_campos_dinamicos['ebitda']
            rentabilidade_total += novos_campos_dinamicos['rentabilidade']

            count += 1
        except:
            pass
    ebitda_medio = ebitda_total / count
    rentabilidade_media = rentabilidade_total / count
    try:
        novo_dre = Dre.objects.get(ano_exercicio=dre.ano_exercicio-1)
        rentabilidade_ano_passado = calcula_campos_dinamicos(novo_dre)['rentabilidade']
    except:
        rentabilidade_ano_passado = 0.0

    # Campos smile
    smiles = {}
    smiles['smile_lucro_liquido'] = select_smile(analise_objetivo.smile_lucro_liquido)
    smiles['smile_rentabilidade_media'] = select_smile(analise_objetivo.smile_rentabilidade_media)
    smiles['smile_rentabilidade_ultimo'] = select_smile(analise_objetivo.smile_rentabilidade_ultimo)
    smiles['smile_rentabilidade_comparada'] = select_smile(analise_objetivo.smile_rentabilidade_comparada)
    smiles['smile_ebitda_medio'] = select_smile(analise_objetivo.smile_ebitda_medio)
    smiles['smile_ebitda_ultimo'] = select_smile(analise_objetivo.smile_ebitda_ultimo)

    dicio_retorno = {'receita': receita_bruta,
                     'receita_': receita_bruta * objetivo.rentabilidade_percentage,
                     'ebitda': campos_dinamicos['ebitda'], 'smiles': smiles,
                     'ebitda_': campos_dinamicos['ebitda'] * objetivo.ebitda_percentage,
                     'lucro_liquido': lucro_liquido,
                     'ebitda_medio': ebitda_medio,
                     'rentabilidade_media': rentabilidade_media,
                     'rentabilidade': campos_dinamicos['rentabilidade'],
                     'rentabilidade_comparada': campos_dinamicos['rentabilidade'] - rentabilidade_ano_passado,
                     'rentabilidade_percentage': objetivo.rentabilidade_percentage * 100,
                     'ebitda_percentage': (objetivo.ebitda_percentage - 1) * 100
    }
    return render(request, 'objetivos/def_objetivos_rentabilidade.html', dicio_retorno)

@login_required
@csrf_exempt
@is_allowed
def salvar_objetivo_de_rentabilidade(request, user):
    if request.method == 'POST':
        # Objetos do banco de dados
        owner = get_object_or_404(User, username=user)
        dre = Dre.objects.all().filter(user=owner).order_by('-ano_exercicio')[0]
        objetivo = ObjetivoRentabilidade.objects.get_or_create(dre_base=dre)[0]
        analise_objetivo = AnaliseObjetivoRentabilidade.objects.get_or_create(objetivo_rentabilidade_base=objetivo)[0]

        # Atualização de campos
        objetivo.rentabilidade_percentage = float(request.POST['rentabilidade_percentage'])
        objetivo.ebitda_percentage = float(request.POST['ebitda_percentage'])
        analise_objetivo.smile_lucro_liquido = request.POST['smile_lucro_liquido']
        analise_objetivo.smile_rentabilidade_media = request.POST['smile_rentabilidade_media']
        analise_objetivo.smile_rentabilidade_ultimo = request.POST['smile_rentabilidade_ultimo']
        analise_objetivo.smile_rentabilidade_comparada = request.POST['smile_rentabilidade_comparada']
        analise_objetivo.smile_ebitda_medio = request.POST['smile_ebitda_medio']
        analise_objetivo.smile_ebitda_ultimo = request.POST['smile_ebitda_ultimo']

        # Salvamento no banco de dados
        objetivo.save()
        analise_objetivo.save()
    return HttpResponse('')

@login_required
@is_allowed
def definir_objetivo_de_endividamento(request, user):
    # Objetos do banco de dados
    owner = get_object_or_404(User, username=user)
    dre = Dre.objects.all().filter(user=owner).order_by('-ano_exercicio')[0]
    objetivo = ObjetivoEndividamento.objects.get_or_create(dre_base=dre)[0]
    analise_objetivo = AnaliseObjetivoEndividamento.objects.get_or_create(objetivo_endividamento_base=objetivo)[0]

    # Campos para exibição
    campos_dinamicos =  calcula_campos_dinamicos(dre)
    lucro = campos_dinamicos['lucro_liquido']

    # Campos smile
    smiles = {}
    smiles['smile_divida'] = select_smile(analise_objetivo.smile_divida)
    smiles['smile_taxa_divida_lucro'] = select_smile(analise_objetivo.smile_taxa_divida_lucro)
    smiles['smile_inadimplencia'] = select_smile(analise_objetivo.smile_inadimplencia)

    dicio_retorno = {
                     'inadimplencia_percentage': (1-objetivo.inadimplencia_percentage)*100,
                     'divida_percentage': (1-objetivo.divida_percentage) * 100,
                     'inadimplencia': dre.inadimplencia,
                     'inadimplencia_': dre.inadimplencia * objetivo.inadimplencia_percentage,
                     'divida': dre.endividamento,
                     'divida_': dre.endividamento * objetivo.divida_percentage,
                     'smiles': smiles,
                     'taxa': dre.endividamento / lucro,
    }
    return render(request, 'objetivos/def_objetivos_endividamento.html', dicio_retorno)

@login_required
@csrf_exempt
@is_allowed
def salvar_objetivo_de_endividamento(request, user):
    if request.method == 'POST':
        # Objetos do banco de dados
        owner = get_object_or_404(User, username=user)
        dre = Dre.objects.all().filter(user=owner).order_by('-ano_exercicio')[0]
        objetivo = ObjetivoEndividamento.objects.get_or_create(dre_base=dre)[0]
        analise_objetivo = AnaliseObjetivoEndividamento.objects.get_or_create(objetivo_endividamento_base=objetivo)[0]


objetivos/templates/objetivos/def_objetivos_endividamento.html
{% extends 'base.html' %}

{% block content %}
{% load l10n %}
<br>
<br>
<hr>
<div class="btn-group mr-2"></div>
<div class="btn-group mr-2"></div>
<div class="btn-group mr-2"></div>
<div class="btn-group mr-2">
    <a href="{% url 'objetivos:objetivo_de_rentabilidade' user=request.user %}" class="href"><button type="button" class="btn btn-sm btn-outline-info">Anterior</button></a>
    <a href="{% url 'objetivos:objetivo_de_custos' user=request.user %}" class="href"><button type="button" class="btn btn-sm btn-outline-info">Próximo</button></a>
    <a href="{% url 'graficos:ped_desempenho' user=request.user %}" class="href"><button type="button" class="btn btn-sm btn-outline-info">Menu</button></a>
</div>
<hr>
<div class="container">
 <div class="row">
     <div class="col-12">
         <div class="card">
               <div class="card-header bg-info text-white">
                 <h2 class="text-center">Definindo Objetivos de Endividamento</h2>
                   <div class="card-header bg-info text-white">
                        <select class="selectpicker form-control form-control-lg">
                     <option data-content="<h5>Crescimento Sustentavel da Receita </h5>"></option>
                       <option data-content="<h5>Manutenção da Receita<h5>"></option>
                       <option data-content="<h5>Outros ...<h5>"></option>
                   </select>
                   </div>
             </div>
<div class="bg"id="wrapper" style="min-height: 575px;">
<div class="content ">
 <div class="row">
     <div class="col-lg-3">
         <div class="specpanel">
             <div class="panel-body">
                 <div class="text-center">
             </div>
         </div>
     </div>
  </div>
</div>
</div>
 <div class="row">
     <div class="col-lg-4 text-center" >
       <div class="card shadow p-3 mb-5 bg-white rounded ">
         <div class="card-body">
                 <div class="specpanel stats">
                     <div class="panel-body h-200">
                         <div class="stats-icon pull-right">
                             <i class="fa fa-line-chart fa-2x"></i>
                         </div>
                         <br>
                     <div class="m-t-xl">
                      <span class="font-bold no-margins" style="text-transform:uppercase; font-size:23px;">
                          Valor de Inadimplência
                     </span>
                             <h5 class="no-margins font-extra-bold text-success" style="font-size:41px; color:#a94442;">R$ {{ inadimplencia | floatformat:2 }}</h5>
                         </div>
                     </div>
                 </div>
         </div>
       </div>
     </div>

         <div class="col-lg-4 text-center">
       <div class="card shadow p-3 mb-5 bg-white rounded ">
         <div class="card-body">
                 <div class="specpanel stats">
                     <div class="panel-body h-200">
                         <div class="stats-icon pull-right">
                             <i class="fa fa-line-chart fa-2x"></i>
                         </div>
                         <div class="m-t-xl">
                           <br>
                      <span class="font-bold no-margins" style="text-transform:uppercase; font-size:20px;">
                         Meta de redução da Inadimplência
                     </span>
                     <br>
                     <br>
                     <div align=center>
                       <input type="number" class="form-control" id="inadimplencia_percentage" oninput="update_receita_estimada()" value="{{inadimplencia_percentage | floatformat:0}}" placeholder="Meta de Inadimplencia" style="width: 90%; display: inline; text-align: center;"> %
                     </div>
                         </div>
                     </div>
                 </div>
         </div>
       </div>
     </div>
       <div class="col-lg-4 text-center">
       <div class="card shadow p-3 mb-5 bg-white rounded ">
         <div class="card-body">
                 <div class="specpanel stats">
                     <div class="panel-body h-200">
                         <div class="stats-icon pull-right">
                             <i class="fa fa-line-chart fa-2x"></i>
                         </div>
                         <br>
                         <div class="m-t-xl">
                      <span class="font-bold no-margins" style="text-transform:uppercase; font-size:19px;">
                         Valor da Inadimplência para próximo exercício
                     </span>
                             <h4 id="inadimplencia_atualizada" class="no-margins font-extra-bold text-success" style="font-size:40px; color:#a94442;">R$ {{inadimplencia_|floatformat:2}}</h4>
                         </div>
                     </div>
                 </div>
         </div>
       </div>
     </div>
     <div class="col-lg-4 text-center">
       <div class="card shadow p-3 mb-5 bg-white rounded ">
         <div class="card-body">
                 <div class="specpanel stats">
                     <div class="panel-body h-200">
                         <div class="stats-icon pull-right">
                             <i class="fa fa-line-chart fa-2x"></i>
                         </div>
                         <div class="m-t-xl">
                      <span class="font-bold no-margins" style="text-transform:uppercase; font-size:20px;">
                         Valor da dívida atual
                     </span>
                          <h4 class="no-margins font-extra-bold text-success" style="font-size:40px; color:#a94442;">R$ {{divida|floatformat:2}}</h4>
                             <br>
                             <br>
                         </div>
                     </div>
                 </div>
         </div>
       </div>
     </div>
     <div class="col-lg-4 text-center">
       <div class="card shadow p-3 mb-5 bg-white rounded ">
         <div class="card-body">
                 <div class="specpanel stats">
                     <div class="panel-body h-200">
                         <div class="stats-icon pull-right">
                             <i class="fa fa-line-chart fa-2x"></i>
                         </div>
                         <br>
                         <div class="m-t-xl">
                      <span class="font-bold no-margins" style="text-transform:uppercase; font-size:23px;">
                          Meta de redução da dívida
                     </span>
                     <br>
                             <div align=center>
                               <input type="number" class="form-control" id="divida_percentage" oninput="update_receita_estimada()" value="{{divida_percentage | floatformat:0}}" placeholder="Meta de Redução de Dívida" style="width: 90%; display: inline; text-align: center;"> %

                             </div>
                         </div>
                     </div>
                 </div>
         </div>
       </div>
     </div>
     <div class="col-lg-4 text-center">
       <div class="card shadow p-3 mb-5 bg-white rounded ">
         <div class="card-body">
                 <div class="specpanel stats">
                     <div class="panel-body h-200">
                         <div class="stats-icon pull-right">
                             <i class="fa fa-line-chart fa-2x"></i>
                         </div>
                         <br>
                         <div class="m-t-xl">
                      <span class="font-bold no-margins" style="text-transform:uppercase; font-size:17px;">
                          Valor da dívida para o próximo exercício
                      </span>
                             <h4 id="divida_atualizada" class="no-margins font-extra-bold text-success" style="font-size:37px; color:#a94442;">R$ {{divida_ |floatformat:2}}</h4>
                         </div>
                     </div>
                 </div>
         </div>
       </div>
     </div>


<!--Cards-->
<div class="container clearfix tl-Spacing">
 <div class="card-responsive col-lg-12 text-center "">
     <div class="card-responsive card shadow-lg p-2 mb-5 rounded">
             <div class="overflow-auto">
               <div class="sticky-top">
                   <table class="table table--light table-dre dre-table::after">
                     <br>
<table id="example" class="stripe row-border order-column" style="width:100%">

<div class="row">
 <div class="col">
 </div>
</div>




<table class="table table-responsive">
<thead class="thead-dark col-lg-12">
 <tr>
   <th scope="col-lg-4">Análise de Endividamento</th>
   <th scope="col-lg-4">Resultado</th>
   <th scope="col-lg-4">Análise </th>
 </tr>
</thead>
<tbody>
 <tr>
   <td>Valor da Dívida</td>
   <td>R$ {{ divida | floatformat:2 }}</td>
   <td>
   <select onchange="update_receita_estimada()" id="smile_divida" class="selectpicker col-lg-12">
     {% for smile in smiles.smile_divida %}
       {{smile|safe}}
     {% endfor %}
 </select>
   </td>

 </tr>
 <tr>
   <td class="text-center">Taxa Dívida/Lucro</td>
   <td>{{ taxa | floatformat:3 }}</td>
   <td>
     <select onchange="update_receita_estimada()" id="smile_taxa_divida_lucro" class="selectpicker col-lg-12">
       {% for smile in smiles.smile_taxa_divida_lucro %}
         {{smile|safe}}
       {% endfor %}
   </select>
   </td>
 </tr>
 <tr>
   <td class="text-center">inadimplência</td>
   <td>R$ {{ inadimplencia | floatformat:2 }}</td>
   <td>
     <select onchange="update_receita_estimada()" id="smile_inadimplencia" class="selectpicker col-lg-12">
       {% for smile in smiles.smile_inadimplencia %}
         {{smile|safe}}
       {% endfor %}
   </select>
   </td>
 </tr>
 <tr>
   <td style="color:white">_______________________________________________________________________ </td>
   <td style="color:white">_______________________________________________________</td>
   <td style="color:white">________________</td>
 </tr>

</tbody>
</table>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<br>
{% endblock content %}

{% block extras_js %}
<script type="text/javascript">
  function update_receita_estimada(){
    var selector_inadimplencia = document.getElementById("inadimplencia_percentage");
    var inadimplencia_id = document.getElementById("inadimplencia_atualizada");
    var selector_divida = document.getElementById("divida_percentage");
    var divida_id = document.getElementById("divida_atualizada");

    var data = {};

    smiles = ['smile_divida', 'smile_taxa_divida_lucro', 'smile_inadimplencia'];
    for (i of smiles){
      smile = document.getElementById(i);
      data[i] = smile.options[smile.selectedIndex].value;
    };
    data['inadimplencia_percentage'] = 1 - parseFloat(selector_inadimplencia.value)/100;
    data['divida_percentage'] =  1 - parseFloat(selector_divida.value)/100;

    $.ajax({
      type: "POST",
      url: './salvar/',
      data: data
    });

    // Atualização de campos
    nova_inadimplencia = (1 - parseFloat(selector_inadimplencia.value)/100)* {{inadimplencia|unlocalize}};
    inadimplencia_id.innerHTML = nova_inadimplencia.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });;
    nova_divida = (1 - parseFloat(selector_divida.value)/100) * {{divida|unlocalize}};
    divida_id.innerHTML = nova_divida.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
  };
</script>
{% endblock extras_js %}