accounts/urls.py
from django.urls import path
#from django.contrib.auth.views import login, logout
#from django.core.urlresolvers import reverse_lazy
from django.conf.urls import url
from accounts.views import register
from django.contrib.auth import views as auth_views
from django.contrib.auth import views as RegisterForm
from django.contrib.auth import views as LoginView
from django.contrib.auth import views as LogoutinView

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(
        template_name='login.html',
        redirect_authenticated_user=True,
        extra_context={
            'next': '/graficos/inicial/user/',
        },
    ),name="login",),
    path('logout/',auth_views.LogoutView.as_view(template_name='index.html'), name="logout"),
    path('cadastre-se/', register,name='register' ),
]

dre/urls.py
from dre import views
from django.urls import path

app_name = 'dre'

urlpatterns = [
    path('<user>/', views.list, name='list'),
    path('<user>/add/', views.create, name='add'),
    path('<user>/<ano>/', views.detail, name='detail'),
    path('<user>/<ano>/edit/', views.edit, name='edit'),
    path('<user>/<ano>/delete/', views.delete, name='delete'),
    path('<user>/api/<ano>/', views.api_save, name='api_save')
]

graficos/urls.py
from graficos import views
from django.urls import path

app_name = 'graficos'

urlpatterns = [
    path('dre/<user>/', views.grafico_dre, name='grafico_dre'),
    path('inicial/<user>/', views.ped_inicial, name='ped_inicial'),
    path('gestao/<user>/', views.ped_gestao, name='ped_gestao'),
    path('desempenho/<user>/', views.ped_desempenho, name='ped_desempenho'),
    path('diagnostico/<user>/', views.ped_diagnostico, name='ped_diagnostico'),
    path('diagnostico/externo/<user>/', views.diagnostico_amb_ext, name='diagnostico_amb_ext'),
    path('diagnostico/interno/<user>/', views.diagnostico_amb_int, name='diagnostico_amb_int')
]

icon/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from core.views import home
from django.urls import path

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    # url(r'^reset/', include('password_reset.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^dre/', include('dre.urls', namespace='dre')),
    path('objetivos/', include('objetivos.urls')),
    path('swot/', include('swot.urls')),
    path('graficos/', include('graficos.urls')),
    path('vendas/', include('vendas.urls')),
    path('processos_produtivo/',include('processos_produtivo.urls')),
    path('pessoa/',include('pessoa.urls')),
    path('processos_produtivo/', include('processos_produtivo.urls')),
    path('pessoa/', include('pessoa.urls')),
    path('mapa/', include('mapa.urls')),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

core/templates/partials/actions.html
<a href="{% url detail pk %}" class="btn btn-primary btn-sm" role="button">
    <span class="glyphicon glyphicon-eye-open" aria-hidden="true" title="Ver"></span>
</a>

{% if request.user.is_authenticated %}

    <a href="{% url edit pk %}" class="btn btn-primary btn-sm" role="button">
        <span class="glyphicon glyphicon-edit" aria-hidden="true" title="Editar"></span>
    </a>
    <a href="{% url delete pk %}" class="btn btn-primary btn-sm" role="button">
        <span class="glyphicon glyphicon-trash" aria-hidden="true" title="Deletar"></span>
    </a>

{% endif %}

core/templates/partials/add_button.html
{% if request.user.is_authenticated %}
    <a class="btn btn-primary TbtnMargin" href="" role="button">
        <span class="glyphicon glyphicon-plus" aria-hidden="true" title="Adicionar"></span> Adicionar
    </a>
{% endif %}

core/templates/partials/links_details.html
<a href="{% url list %}" class="btn btn-primary btn-sm" role="button">
    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true" title="Voltar"></span>
</a>

{% if request.user.is_authenticated %}

    <a href="{% url edit pk %}" class="btn btn-primary btn-sm" role="button">
        <span class="glyphicon glyphicon-edit" aria-hidden="true" title="Editar"></span>
    </a>
    <a href="{% url delete pk %}" class="btn btn-primary btn-sm" role="button">
        <span class="glyphicon glyphicon-trash" aria-hidden="true" title="Deletar"></span>
    </a>

{% endif %}

core/templates/partials/navbar.html
{% load static %}
<!-- Fixed navbar -->
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="/">
        <img src="{% static 'img/logo_sevilha_vetor_curva (1).png' %}"><small class="text-secondary">   by ICON </small>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              {% if request.user.is_authenticated %}
                <a class="nav-link" href="/dre/{{ request.user }}"></a>
              {% else %}
                <a class="nav-link" href="{% url 'accounts:login' %}"></a>
              {% endif %}
            </li>
            <li class="nav-item">
              {% if request.user.is_authenticated %}
                <a class="nav-link" href="{% url 'graficos:ped_inicial' user=request.user %}">Menu Inicial</a>
              {% else %}
                <a class="nav-link" href="{% url 'accounts:login' %}">Menu Inicial</a>
              {% endif %}
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}

            <li class="nav-item">
                <a class="nav-link" href="#">{{ request.user }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">Sair</a>
            </li>

            {% else %}
            <!--li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            </li-->
            {% endif %}
        </ul>
    </div>
</nav>

core/templates/partials/paginator.html
<div class="row text-center">
    <ul class="pagination">
        {% if page_objects.has_previous %}
            <li>
                <a href="?page={{ page_objects.previous_page_number }}{% if request.GET.search_box %}&search_box={{ request.GET.search_box }}{% endif %}">&laquo;
                    anterior</a>
            </li>
        {% endif %}

        {% for pg in page_range %}
            {% if page_objects.number == pg %}
                <li class="active"><a href="?page={{ pg }}{% if request.GET.search_box %}&search_box={{ request.GET.search_box }}{% endif %}">{{ pg }}</a></li>
            {% else %}
                <li><a href="?page={{ pg }}{% if request.GET.search_box %}&search_box={{ request.GET.search_box }}{% endif %}">{{ pg }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_objects.has_next %}
            <li>
                <a href="?page={{ page_objects.next_page_number }}{% if request.GET.search_box %}&search_box={{ request.GET.search_box }}{% endif %}">&raquo;
                    seguinte</a>
            </li>
        {% endif %}
    </ul>
</div>